CREATE TABLE IF NOT EXISTS genres (
                                   genre_id INTEGER PRIMARY KEY,
                                   name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa (
                                   mpa_id INTEGER PRIMARY KEY,
                                   name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
                                     film_id INTEGER GENERATED BY DEFAULT as IDENTITY PRIMARY KEY,
                                     name varchar NOT NULL,
                                     description varchar(200),
                                     release_date date NOT NULL,
                                     rate INTEGER,
                                     duration varchar NOT NULL,
                                     mpa_id integer REFERENCES mpa (mpa_id),
                                     CONSTRAINT film_info UNIQUE(name, release_date, duration)

);

CREATE TABLE IF NOT EXISTS users (
                                     user_id INTEGER GENERATED BY DEFAULT as IDENTITY PRIMARY KEY,
                                     name varchar NOT NULL,
                                     login varchar NOT NULL,
                                     email varchar NOT NULL,
                                     birthday date NOT NULL,
                                     UNIQUE (login),
                                     UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS friends (
                                    user_id INTEGER REFERENCES users (user_id),
                                    friend_id INTEGER REFERENCES users (user_id),
                                    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS likes (
                                    user_id INTEGER REFERENCES users (user_id),
                                    film_id INTEGER REFERENCES films (film_id),
                                    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
                                     film_id INTEGER,
                                     genre_id INTEGER,
                                     PRIMARY KEY (film_id, genre_id)
);
